# configUtil.py
#---------------------------------------------------------------------------
# this module will maintain the lookup index and their literal string representation 
# so each variable can be accessed easier in the code.
# TODO: consider to use configparser or other lib for better configuration management
#---------------------------------------------------------------------------

# For input files only
LAYOUT_FILE_BORDER              = 'LAYOUT_FILE_BORDER'
LAYOUT_FILE_EMPTY_SPACE         = 'LAYOUT_FILE_EMPTY_SPACE'
LAYOUT_FILE_EXIT                = 'LAYOUT_FILE_EXIT'
LAYOUT_FILE_OBSTACLE            = 'LAYOUT_FILE_OBSTACLE'
LAYOUT_FILE_EMPTY_CELL          = 'LAYOUT_FILE_EMPTY_CELL'

# display related
LAYOUT_DISPLAY_BORDER           = 'LAYOUT_DISPLAY_BORDER' 
LAYOUT_DISPLAY_EMPTY_SPACE      = 'LAYOUT_DISPLAY_EMPTY_SPACE' 
LAYOUT_DISPLAY_EXIT             = 'LAYOUT_DISPLAY_EXIT' 
LAYOUT_DISPLAY_OBSTACLE         = 'LAYOUT_DISPLAY_OBSTACLE'
LAYOUT_DISPLAY_EMPTY_CELL       = 'LAYOUT_DISPLAY_EMPTY_CELL' 
LAYOUT_SENIOR_COLOR             = 'LAYOUT_SENIOR_COLOR' 
LAYOUT_NON_SENIOR_COLOR         = 'LAYOUT_NON_SENIOR_COLOR' 

# below items will be have a color picker icon
LAYOUT_DISPLAY_BORDER_COLORCONFIG               = 'LAYOUT_DISPLAY_BORDER_COLORCONFIG'
LAYOUT_DISPLAY_EMPTY_SPACE_COLORCONFIG          = 'LAYOUT_DISPLAY_EMPTY_SPACE_COLORCONFIG'
LAYOUT_DISPLAY_EXIT_COLORCONFIG                 = 'LAYOUT_DISPLAY_EXIT_COLORCONFIG'
LAYOUT_DISPLAY_OBSTACLE_COLORCONFIG             = 'LAYOUT_DISPLAY_OBSTACLE_COLORCONFIG'
LAYOUT_DISPLAY_EMPTY_CELL_COLORCONFIG           = 'LAYOUT_DISPLAY_EMPTY_CELL_COLORCONFIG'
LAYOUT_SENIOR_COLOR_COLORCONFIG                 = 'LAYOUT_SENIOR_COLOR_COLORCONFIG'    
LAYOUT_NON_SENIOR_COLOR_COLORCONFIG             = 'LAYOUT_NON_SENIOR_COLOR_COLORCONFIG'

# all display related items will be configurable.
LAYOUT_DISPLAY_BORDER_CONFIG           = 'LAYOUT_DISPLAY_BORDER_CONFIG'
LAYOUT_DISPLAY_EMPTY_SPACE_CONFIG      = 'LAYOUT_DISPLAY_EMPTY_SPACE_CONFIG'
LAYOUT_DISPLAY_EXIT_CONFIG             = 'LAYOUT_DISPLAY_EXIT_CONFIG'
LAYOUT_DISPLAY_OBSTACLE_CONFIG         = 'LAYOUT_DISPLAY_OBSTACLE_CONFIG'
LAYOUT_DISPLAY_EMPTY_CELL_CONFIG       = 'LAYOUT_DISPLAY_EMPTY_CELL_CONFIG'
LAYOUT_SENIOR_COLOR_CONFIG             = 'LAYOUT_SENIOR_COLOR_CONFIG'
LAYOUT_NON_SENIOR_COLOR_CONFIG         = 'LAYOUT_NON_SENIOR_COLOR_CONFIG'


LAYOUT_NUMBER_BORDER            = 'LAYOUT_NUMBER_BORDER'
LAYOUT_NUMBER_EMPTY_SPACE       = 'LAYOUT_NUMBER_EMPTY_SPACE'
LAYOUT_NUMBER_EXIT              = 'LAYOUT_NUMBER_EXIT'
LAYOUT_NUMBER_OBSTACLE          = 'LAYOUT_NUMBER_OBSTACLE'
LAYOUT_NUMBER_EMPTY_CELL        = 'LAYOUT_NUMBER_EMPTY_CELL'

# control the real graph displayed in the GUI
LAYOUT_CELL_SIZE                = 'LAYOUT_CELL_SIZE'
LAYOUT_CELL_ROUND_RECT_RADIUS   = 'LAYOUT_CELL_ROUND_RECT_RADIUS'

LAYOUT_CELL_SIZE_CONFIG                 = 'LAYOUT_CELL_SIZE_CONFIG'
LAYOUT_CELL_ROUND_RECT_RADIUS_CONFIG    = 'LAYOUT_CELL_ROUND_RECT_RADIUS_CONFIG'

LAYOUT_CELL_TYPE_BORDER         = 'LAYOUT_CELL_TYPE_BORDER'
LAYOUT_CELL_TYPE_EMPTY_SPACE    = 'LAYOUT_CELL_TYPE_EMPTY_SPACE'
LAYOUT_CELL_TYPE_EXIT           = 'LAYOUT_CELL_TYPE_EXIT'
LAYOUT_CELL_TYPE_OBSTACLE       = 'LAYOUT_CELL_TYPE_OBSTACLE'
LAYOUT_CELL_TYPE_EMPTY_CELL     = 'LAYOUT_CELL_TYPE_EMPTY_CELL'

# in meters, will be used to calculate the number of evacuation zone
EVACUATION_ZONE_DIMENSION = 'EVACUATION_ZONE_DIMENSION'
EVACUATION_ZONE_DIMENSION_CONFIG = 'EVACUATION_ZONE_DIMENSION_CONFIG'

# cell automata size in meters
# each cell in layout file is representing 0.5m^2
CELL_SIZE = 'CELL_SIZE'
CELL_SIZE_CONFIG = 'CELL_SIZE_CONFIG'

# pedestrian per square meter(0-4)
PEDESTRIAN_PER_SQUARE_METER = 'PEDESTRIAN_PER_SQUARE_METER'
PEDESTRIAN_PER_SQUARE_METER_CONFIG = 'PEDESTRIAN_PER_SQUARE_METER_CONFIG'

# predefined number of PEDESTRIAN in current scenario
NUMBER_OF_PEDESTRIAN = 'NUMBER_OF_PEDESTRIAN'
NUMBER_OF_PEDESTRIAN_CONFIG = 'NUMBER_OF_PEDESTRIAN_CONFIG'

#percentage of senior people (0%~100%)
SENIOR_PEDESTRIAN_PERCENTAGE = 'SENIOR_PEDESTRIAN_PERCENTAGE'
SENIOR_PEDESTRIAN_PERCENTAGE_CONFIG = 'SENIOR_PEDESTRIAN_PERCENTAGE_CONFIG'

# Horizontal or vertical distance
HORI_VERT_DISTANCE = 'HORI_VERT_DISTANCE'
HORI_VERT_DISTANCE_CONFIG = 'HORI_VERT_DISTANCE_CONFIG'

DIAGONAL_DISTANCE = 'DIAGONAL_DISTANCE'
DIAGONAL_DISTANCE_CONFIG = 'DIAGONAL_DISTANCE_CONFIG'

#SIMULATION TIME INTERVAL (in seconds)
SIMULATION_TIME_INTERVAL = 'SIMULATION_TIME_INTERVAL'
SIMULATION_TIME_INTERVAL_CONFIG = 'SIMULATION_TIME_INTERVAL_CONFIG'

# SIMULATION CYCLE (Tau)
SIMULATION_CYCLE = 'SIMULATION_CYCLE'
SIMULATION_CYCLE_CONFIG = 'SIMULATION_CYCLE_CONFIG'

#PEDESTRAIN SPEED m/s
NORMAL_PEDESTRIAN_SPEED = 'NORMAL_PEDESTRIAN_SPEED'
NORMAL_PEDESTRIAN_SPEED_CONFIG = 'NORMAL_PEDESTRIAN_SPEED_CONFIG'

SENIOR_PEDESTRIAN_SPEED = 'SENIOR_PEDESTRIAN_SPEED'
SENIOR_PEDESTRIAN_SPEED_CONFIG = 'SENIOR_PEDESTRIAN_SPEED_CONFIG'

# parameter for the exit choice model
EXIT_CHOICE_MODEL_ALPHA_DIAGONAL = 'EXIT_CHOICE_MODEL_ALPHA_DIAGONAL'
EXIT_CHOICE_MODEL_ALPHA_DIAGONAL_CONFIG = 'EXIT_CHOICE_MODEL_ALPHA_DIAGONAL_CONFIG'
EXIT_CHOICE_MODEL_ALPHA_NON_DIAGONAL = 'EXIT_CHOICE_MODEL_ALPHA_NON_DIAGONAL'
EXIT_CHOICE_MODEL_ALPHA_NON_DIAGONAL_CONFIG = 'EXIT_CHOICE_MODEL_ALPHA_NON_DIAGONAL_CONFIG'
EXIT_CHOICE_MODEL_BETA = 'EXIT_CHOICE_MODEL_BETA'
EXIT_CHOICE_MODEL_BETA_CONFIG = 'EXIT_CHOICE_MODEL_BETA_CONFIG'
EXIT_CHOICE_MODEL_GAMMA = 'EXIT_CHOICE_MODEL_GAMMA'
EXIT_CHOICE_MODEL_GAMMA_CONFIG = 'EXIT_CHOICE_MODEL_GAMMA_CONFIG'
EXIT_CHOICE_MODEL_THETA = 'EXIT_CHOICE_MODEL_THETA'
EXIT_CHOICE_MODEL_THETA_CONFIG = 'EXIT_CHOICE_MODEL_THETA_CONFIG'

# number of exit in current layout
#NUMBER_OF_EXIT = 8

# Parameter for the pedestrain movement model
PEDESTRIAN_MOVEMENT_MODEL_DELTA = 'PEDESTRIAN_MOVEMENT_MODEL_DELTA'
PEDESTRIAN_MOVEMENT_MODEL_DELTA_CONFIG = 'PEDESTRIAN_MOVEMENT_MODEL_DELTA_CONFIG'
PEDESTRIAN_MOVEMENT_MODEL_PHI = 'PEDESTRIAN_MOVEMENT_MODEL_PHI'
PEDESTRIAN_MOVEMENT_MODEL_PHI_CONFIG = 'PEDESTRIAN_MOVEMENT_MODEL_PHI_CONFIG'
PEDESTRIAN_MOVEMENT_MODEL_EPSILON = 'PEDESTRIAN_MOVEMENT_MODEL_EPSILON'
PEDESTRIAN_MOVEMENT_MODEL_EPSILON_CONFIG = 'PEDESTRIAN_MOVEMENT_MODEL_EPSILON_CONFIG'

# DIRECTION
DIRECTION_UP                = 'DIRECTION_UP'
DIRECTION_DOWN              = 'DIRECTION_DOWN'
DIRECTION_LEFT              = 'DIRECTION_LEFT'
DIRECTION_RIGHT             = 'DIRECTION_RIGHT'
DIRECTION_UPLEFT            = 'DIRECTION_UPLEFT'
DIRECTION_UPRIGHT           = 'DIRECTION_UPRIGHT'
DIRECTION_DOWNLEFT          = 'DIRECTION_DOWNLEFT'
DIRECTION_DOWNRIGHT         = 'DIRECTION_DOWNRIGHT'
DIRECTION_CENTER            = 'DIRECTION_CENTER'

